# Generated by Django 3.1.5 on 2021-03-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20210228_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(default='old', max_length=500),
            preserve_default=False,
        ),
    ]
